# Generated by Django 5.1.6 on 2026-03-25 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='课程名称')),
                ('category', models.CharField(max_length=100, verbose_name='课程类别')),
                ('teacher', models.CharField(max_length=100, verbose_name='讲师')),
                ('duration_hours', models.IntegerField(default=2, verbose_name='学时')),
                ('mode', models.CharField(default='线上+实训', max_length=50, verbose_name='培训形式')),
                ('description', models.TextField(blank=True, verbose_name='课程简介')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '培训课程',
                'verbose_name_plural': '培训课程',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee', models.CharField(max_length=100, verbose_name='学员')),
                ('department', models.CharField(max_length=100, verbose_name='部门')),
                ('score', models.IntegerField(default=0, verbose_name='考核成绩')),
                ('passed', models.BooleanField(default=False, verbose_name='是否通过')),
                ('completed_at', models.DateField(verbose_name='完成日期')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='training.trainingcourse', verbose_name='课程')),
            ],
            options={
                'verbose_name': '培训记录',
                'verbose_name_plural': '培训记录',
                'ordering': ['-completed_at'],
            },
        ),
    ]
