# Generated by Django 5.1.6 on 2026-03-25 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='设备名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='设备编号')),
                ('category', models.CharField(max_length=100, verbose_name='设备类别')),
                ('mine_name', models.CharField(max_length=150, verbose_name='所在矿井')),
                ('location', models.CharField(max_length=200, verbose_name='安装位置')),
                ('health_status', models.CharField(choices=[('excellent', '优'), ('good', '良'), ('warning', '预警'), ('danger', '危险')], default='good', max_length=20, verbose_name='健康状态')),
                ('health_score', models.IntegerField(default=85, verbose_name='健康评分')),
                ('runtime_hours', models.IntegerField(default=0, verbose_name='累计运行小时')),
                ('next_maintenance_date', models.DateField(verbose_name='下次维护日期')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '设备台账',
                'verbose_name_plural': '设备台账',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='诊断主题')),
                ('symptom', models.TextField(verbose_name='故障现象')),
                ('diagnosis', models.TextField(verbose_name='专家诊断')),
                ('recommendation', models.TextField(verbose_name='处置建议')),
                ('expert_name', models.CharField(max_length=100, verbose_name='专家姓名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='equipment.equipment', verbose_name='设备')),
            ],
            options={
                'verbose_name': '远程诊断案例',
                'verbose_name_plural': '远程诊断案例',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ARSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(max_length=50, unique=True, verbose_name='AR会话编号')),
                ('glasses_model', models.CharField(max_length=100, verbose_name='AR眼镜型号')),
                ('field_engineer', models.CharField(max_length=100, verbose_name='现场人员')),
                ('remote_expert', models.CharField(max_length=100, verbose_name='后台专家')),
                ('status', models.CharField(default='已建立连接', max_length=50, verbose_name='会话状态')),
                ('interaction_note', models.TextField(verbose_name='交互记录')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_sessions', to='equipment.equipment', verbose_name='设备')),
            ],
            options={
                'verbose_name': 'AR远程协作',
                'verbose_name_plural': 'AR远程协作',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentSensorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=100, verbose_name='诊断传感器类型')),
                ('deploy_position', models.CharField(max_length=200, verbose_name='部署位置')),
                ('purpose', models.CharField(max_length=200, verbose_name='部署目的')),
                ('status', models.CharField(default='已部署', max_length=50, verbose_name='部署状态')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_plans', to='equipment.equipment', verbose_name='设备')),
            ],
            options={
                'verbose_name': '诊断传感器部署',
                'verbose_name_plural': '诊断传感器部署',
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector', models.CharField(max_length=100, verbose_name='巡检人')),
                ('result', models.CharField(max_length=100, verbose_name='巡检结论')),
                ('vibration_value', models.FloatField(default=0, verbose_name='振动值')),
                ('temperature_value', models.FloatField(default=0, verbose_name='温度值')),
                ('note', models.TextField(blank=True, verbose_name='说明')),
                ('inspected_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='equipment.equipment', verbose_name='设备')),
            ],
            options={
                'verbose_name': '巡检记录',
                'verbose_name_plural': '巡检记录',
                'ordering': ['-inspected_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='工单标题')),
                ('priority', models.CharField(max_length=50, verbose_name='优先级')),
                ('status', models.CharField(choices=[('open', '待处理'), ('processing', '处理中'), ('done', '已完成')], default='open', max_length=20, verbose_name='工单状态')),
                ('assignee', models.CharField(max_length=100, verbose_name='维修人员')),
                ('summary', models.TextField(verbose_name='问题说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='equipment.equipment', verbose_name='设备')),
            ],
            options={
                'verbose_name': '维修工单',
                'verbose_name_plural': '维修工单',
                'ordering': ['-created_at'],
            },
        ),
    ]
