# Generated by Django 5.1.6 on 2026-03-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('level', models.CharField(default='info', max_length=20, verbose_name='级别')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '平台公告',
                'verbose_name_plural': '平台公告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='看板主题')),
                ('value', models.CharField(max_length=100, verbose_name='指标值')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '首页指标卡片',
                'verbose_name_plural': '首页指标卡片',
            },
        ),
        migrations.CreateModel(
            name='ExpertKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='知识分类')),
                ('title', models.CharField(max_length=200, verbose_name='知识标题')),
                ('content', models.TextField(verbose_name='知识内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '专家知识库',
                'verbose_name_plural': '专家知识库',
                'ordering': ['category', 'title'],
            },
        ),
    ]
