# Generated by Django 5.1.6 on 2026-03-25 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mine_name', models.CharField(max_length=150, verbose_name='矿井名称')),
                ('gas_concentration', models.FloatField(default=0, verbose_name='气体浓度')),
                ('temperature', models.FloatField(default=0, verbose_name='温度')),
                ('humidity', models.FloatField(default=0, verbose_name='湿度')),
                ('pressure', models.FloatField(default=0, verbose_name='压力')),
                ('risk_level', models.CharField(default='低', max_length=50, verbose_name='风险等级')),
                ('recorded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '环境监测',
                'verbose_name_plural': '环境监测',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='FillProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='工艺名称')),
                ('process_type', models.CharField(choices=[('paste', '膏体充填'), ('tailings', '尾砂充填'), ('gangue', '原矸充填')], max_length=20, verbose_name='工艺类型')),
                ('mine_name', models.CharField(max_length=150, verbose_name='矿井/站点')),
                ('status', models.CharField(default='运行中', max_length=50, verbose_name='运行状态')),
                ('design_capacity', models.FloatField(default=0, verbose_name='设计能力（m³/h）')),
                ('current_flow', models.FloatField(default=0, verbose_name='当前流量（m³/h）')),
                ('concentration', models.FloatField(default=0, verbose_name='浓度（%）')),
                ('pipeline_pressure', models.FloatField(default=0, verbose_name='管路压力（MPa）')),
                ('data_quality', models.IntegerField(default=95, verbose_name='数据质量分')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '充填工艺',
                'verbose_name_plural': '充填工艺',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='传感器名称')),
                ('sensor_type', models.CharField(choices=[('vibration', '振动传感器'), ('temperature', '温度传感器'), ('pressure', '压力传感器'), ('flow', '流量传感器'), ('level', '料位传感器'), ('gas', '气体传感器'), ('humidity', '湿度传感器')], max_length=30, verbose_name='传感器类型')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='设备编码')),
                ('location', models.CharField(max_length=200, verbose_name='安装位置')),
                ('unit', models.CharField(default='', max_length=30, verbose_name='单位')),
                ('current_value', models.FloatField(default=0, verbose_name='当前值')),
                ('threshold_low', models.FloatField(default=0, verbose_name='下限')),
                ('threshold_high', models.FloatField(default=0, verbose_name='上限')),
                ('is_online', models.BooleanField(default=True, verbose_name='在线状态')),
                ('last_report_time', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='monitoring.fillprocess', verbose_name='所属工艺')),
            ],
            options={
                'verbose_name': '传感器',
                'verbose_name_plural': '传感器',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='报警标题')),
                ('level', models.CharField(choices=[('low', '一般'), ('medium', '注意'), ('high', '严重'), ('critical', '紧急')], max_length=20, verbose_name='报警级别')),
                ('description', models.TextField(verbose_name='报警描述')),
                ('resolved', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.fillprocess', verbose_name='所属工艺')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.sensor', verbose_name='关联传感器')),
            ],
            options={
                'verbose_name': '报警事件',
                'verbose_name_plural': '报警事件',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='采集值')),
                ('quality_score', models.IntegerField(default=100, verbose_name='质量分')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitoring.sensor', verbose_name='传感器')),
            ],
            options={
                'verbose_name': '传感器读数',
                'verbose_name_plural': '传感器读数',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='监控设备名称')),
                ('location', models.CharField(max_length=200, verbose_name='安装位置')),
                ('stream_url', models.CharField(blank=True, max_length=255, verbose_name='视频流地址')),
                ('status', models.CharField(default='在线', max_length=50, verbose_name='状态')),
                ('last_ping', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_devices', to='monitoring.fillprocess', verbose_name='所属工艺')),
            ],
            options={
                'verbose_name': '监控设备',
                'verbose_name_plural': '监控设备',
            },
        ),
    ]
