# Generated by Django 5.1.6 on 2026-03-25 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FillProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='项目编号')),
                ('owner', models.CharField(max_length=100, verbose_name='负责人')),
                ('mine_name', models.CharField(max_length=150, verbose_name='实施矿井')),
                ('stage', models.CharField(choices=[('initiation', '立项'), ('design', '设计'), ('procurement', '采购'), ('construction', '施工'), ('commissioning', '调试'), ('acceptance', '验收'), ('operation', '运维')], default='initiation', max_length=30, verbose_name='项目阶段')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='项目预算')),
                ('progress', models.IntegerField(default=0, verbose_name='整体进度(%)')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='计划结束日期')),
                ('description', models.TextField(blank=True, verbose_name='项目说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '充填项目',
                'verbose_name_plural': '充填项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcceptanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_stage', models.CharField(max_length=100, verbose_name='验收阶段')),
                ('score', models.IntegerField(default=0, verbose_name='验收分数')),
                ('result', models.CharField(max_length=100, verbose_name='验收结果')),
                ('summary', models.TextField(verbose_name='验收总结')),
                ('accepted_at', models.DateField(verbose_name='验收日期')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='lifecycle.fillproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '验收记录',
                'verbose_name_plural': '验收记录',
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='里程碑')),
                ('milestone_date', models.DateField(verbose_name='节点日期')),
                ('completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='lifecycle.fillproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '里程碑',
                'verbose_name_plural': '里程碑',
                'ordering': ['milestone_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文档名称')),
                ('category', models.CharField(max_length=100, verbose_name='文档类别')),
                ('version', models.CharField(default='V1.0', max_length=50, verbose_name='版本')),
                ('file_note', models.TextField(blank=True, verbose_name='文件说明')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lifecycle.fillproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目文档',
                'verbose_name_plural': '项目文档',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务名称')),
                ('owner', models.CharField(max_length=100, verbose_name='责任人')),
                ('stage', models.CharField(max_length=30, verbose_name='阶段')),
                ('status', models.CharField(choices=[('todo', '待开始'), ('doing', '进行中'), ('done', '已完成'), ('delayed', '延期')], default='todo', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('due_date', models.DateField(verbose_name='截止日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='lifecycle.fillproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目任务',
                'verbose_name_plural': '项目任务',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='RiskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='风险名称')),
                ('level', models.CharField(max_length=50, verbose_name='风险等级')),
                ('status', models.CharField(default='监控中', max_length=50, verbose_name='处置状态')),
                ('strategy', models.TextField(verbose_name='应对措施')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='lifecycle.fillproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目风险',
                'verbose_name_plural': '项目风险',
                'ordering': ['-created_at'],
            },
        ),
    ]
